// client/src/components/sequences/SeqRefChip.vue
<template>
  <v-chip
    :text="`${db.code}:${accession}`"
    :href="SeqReference.link(seqRef)"
    target="_blank"
    v-bind="$attrs"
    :color="is_origin ? 'success' : undefined"
    :prepend-icon="is_origin ? 'mdi-arrow-down' : undefined"
    :title="is_origin ? 'Sequence origin' : 'External sequence reference'"
  />
</template>

<script setup lang="ts">
import { SeqReference } from '@/api/adapters'

const { seqRef } = defineProps<{ seqRef: SeqReference }>()
const { accession, db, is_origin } = seqRef
</script>

<style scoped lang="scss"></style>

// client/src/features/sequences/components/SeqRefChip.tsx
import { SeqReference } from '@/api'

export function SeqRefChip({ seqRef }: { seqRef: SeqReference }, context: { attrs?: object }) {
  const { db, accession, is_origin } = seqRef
  return (
    <v-chip
      text={`${db.code}: ${accession}`}
      href={SeqReference.link(seqRef)}
      target="_blank"
      color={is_origin ? 'success' : undefined}
      prepend-icon={is_origin ? 'mdi-arrow-down' : undefined}
      {...context.attrs}
    />
  )
}

export default SeqRefChip
